// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfSkiYXyeayxEjzZ7H7mEE8fHQ483arX8',
    appId: '1:241227347252:web:330b16d61f2c66c054e161',
    messagingSenderId: '241227347252',
    projectId: 'baettori-244a9',
    authDomain: 'baettori-244a9.firebaseapp.com',
    storageBucket: 'baettori-244a9.appspot.com',
    measurementId: 'G-3XRQJLLTMV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG8KvypXkKDENxS7PLuKvR-6H8dm139Is',
    appId: '1:241227347252:android:1a13381ed5bbef1f54e161',
    messagingSenderId: '241227347252',
    projectId: 'baettori-244a9',
    storageBucket: 'baettori-244a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAioyBGXNghGNVNPqU54GWoZTCfbf5Xj5w',
    appId: '1:241227347252:ios:32827928179e8c4554e161',
    messagingSenderId: '241227347252',
    projectId: 'baettori-244a9',
    storageBucket: 'baettori-244a9.appspot.com',
    iosBundleId: 'com.example.baettori',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAioyBGXNghGNVNPqU54GWoZTCfbf5Xj5w',
    appId: '1:241227347252:ios:32827928179e8c4554e161',
    messagingSenderId: '241227347252',
    projectId: 'baettori-244a9',
    storageBucket: 'baettori-244a9.appspot.com',
    iosBundleId: 'com.example.baettori',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfSkiYXyeayxEjzZ7H7mEE8fHQ483arX8',
    appId: '1:241227347252:web:667aebb8729e51d154e161',
    messagingSenderId: '241227347252',
    projectId: 'baettori-244a9',
    authDomain: 'baettori-244a9.firebaseapp.com',
    storageBucket: 'baettori-244a9.appspot.com',
    measurementId: 'G-6DFD469JBF',
  );

}